### ISSUE TITLE
Can't run tests -- missing .fastlegs configuration file

### ISSUE THREAD

**Issue by Wilfred** [didit-tech/FastLegS#15]
```
$ make test

FastLegS: Please enter your Postgres credentials and a database for us to create.

pg username: foo
pg password: 
pg database: (fastlegs_test) 
pg host: (localhost) 
pg port: (5432) 

   100% 36 tests


   integration_test.js integrates: Error: EBADF, Bad file descriptor '/usr/local/lib/node_modules/FastLegS/test/integration/../../.fastlegs'
    at Object.openSync (fs.js:221:18)
    at Object.readFileSync (fs.js:112:15)
    at /usr/local/lib/node_modules/FastLegS/test/integration/integration_test.js:23:21
    at next (/usr/local/lib/node_modules/expresso/bin/expresso:844:25)
    at runSuite (/usr/local/lib/node_modules/expresso/bin/expresso:862:6)
    at check (/usr/local/lib/node_modules/expresso/bin/expresso:766:16)
    at runFile (/usr/local/lib/node_modules/expresso/bin/expresso:770:10)
    at Array.forEach (native)
    at runFiles (/usr/local/lib/node_modules/expresso/bin/expresso:747:13)
    at run (/usr/local/lib/node_modules/expresso/bin/expresso:715:5)


   Failures: 1


make: *** [test-integration] Error 123
```

Should be pretty straightforward to fix, but it's not immediately clear to me what should be in the file.

**Comment by malkomalko** [comment]
I'm pretty sure this happens when you enter in bad configuration or if the database already exists.  This should be an easy fix.  Can you confirm that the database didn't exist and that the user/pass is correct?

**Comment by Wilfred** [comment]
I'm sorry, I realise that there was actually a database of the same name. Is it necessary to prompt for a database name, couldn't the tests just choose a unique name?
