### ISSUE TITLE
Nested queries?

### ISSUE THREAD

**Issue by hugovincent** [didit-tech/FastLegS#22]
Are nested queries supposed to work? For example, let's say I have a .find query, and in its results callback I issue further query; I consistently get errors of the type:

`````` net.js:391
    throw new Error('Socket is not writable');
          ^
Error: Socket is not writable
    at Socket._writeOut (net.js:391:11)
    at Socket.write (net.js:377:17)
    at [object Object].query (/usr/local/lib/node_modules/FastLegS/node_modules/pg/lib/connection.js:96:15)
    at [object Object].submit (/usr/local/lib/node_modules/FastLegS/node_modules/pg/lib/query.js:96:16)
    at [object Object]._pulseQueryQueue (/usr/local/lib/node_modules/FastLegS/node_modules/pg/lib/client.js:129:24)
    at [object Object].query (/usr/local/lib/node_modules/FastLegS/node_modules/pg/lib/client.js:153:8)
    at Client.<anonymous> (/usr/local/lib/node_modules/FastLegS/lib/fast_legs/client.js:25:17)
    at Client.emit (events.js:67:17)
    at /usr/local/lib/node_modules/FastLegS/lib/fast_legs/base.js:225:18
    at Object.create (/usr/local/lib/node_modules/FastLegS/lib/fast_legs/base.js:45:3)```
``````

**Comment by thadclay** [comment]
Could you provide an example?

**Comment by hugovincent** [comment]
Apologies; it became clear that I was accidentally disconnecting the client due to a misused .on('drain') hook. My bad.
