### ISSUE TITLE
TypeError: Object 1 has no method 'forEach'

### ISSUE THREAD

**Issue by gahula** [didit-tech/FastLegS#55]
TypeError: Object 1 has no method 'forEach'
    at buildOperator (/home/dc/webapps/app/node_modules/FastLegS/lib/adapters/pg/statements.js:186:11)
    at /home/a9designs/webapps/gahoola_desktop/node_modules/FastLegS/lib/adapters/pg/statements.js:271:28
    at /home/dc/webapps/app/node_modules/FastLegS/node_modules/underscore/underscore.js:99:42
    at _.each._.forEach (/home/dc/webapps/app/node_modules/FastLegS/node_modules/underscore/underscore.js:86:24)
    at Function._.map._.collect (/home/dc/webapps/app/node_modules/FastLegS/node_modules/underscore/underscore.js:98:5)
    at _.(anonymous function) [as map](/home/dc/webapps/app/node_modules/FastLegS/node_modules/underscore/underscore.js:1069:39)
    at buildWhereClause (/home/dc/webapps/app/node_modules/FastLegS/lib/adapters/pg/statements.js:267:18)
    at Object.exports.select (/home/dc/webapps/app/node_modules/FastLegS/lib/adapters/pg/statements.js:26:16)
    at findQuery (/home/dc/webapps/app/node_modules/FastLegS/lib/adapters/pg/base.js:61:32)
    at loadSchema (/home/dc/webapps/app/node_modules/FastLegS/lib/adapters/pg/base.js:248:5)

**Comment by thadclay** [comment]
@gahula Going to need some more details to look into this. Please provide an example.

**Comment by gahula** [comment]
{ 'id.in': '16', is_active: true } //where
{ only: [ '*' ], //options
  limit: 1,
  offset: undefined,
  order: undefined,
  include: undefined }

model.find(where, options, function(err, res) {

```
        if(err) {
            return callback(err, []);
        } else {
            if(!_.isEmpty(res)) {
                return callback([], res);
            } else {
                return callback([], []);
            }   
        }
    });
```

**Comment by gahula** [comment]
Problem was the .in in the where.  However, thank you for your response.
